from crewai import Task
from agents import research_agent, analysis_agent, report_agent

def create_tasks(company_name: str):
    research_task = Task(
        description=f"""
            Research the following company or startup thoroughly: {company_name}

            Find and compile:
            - What the company does (product, service, business model)
            - Who founded it and when
            - Funding history (rounds, amounts, investors)
            - Current market size and target audience
            - Top 3-5 direct competitors and what makes each one different
            - Recent news (last 6 months)
            - Any notable achievements, partnerships, or controversies

            Be specific. Use real numbers where available.
            Do not speculate. Only include what you actually found.
        """,
        expected_output="""
            A structured research brief with clear sections:
            - Company Overview
            - Founding & Team
            - Funding History
            - Market & Audience
            - Competitors
            - Recent News
            - Notable Facts

            Each section should have specific, factual bullet points.
            No vague statements. No filler.
        """,
        agent=research_agent, 
    )

    analysis_task = Task(
        description=f"""
            You have received research about {company_name}.
            Using ONLY the information in that research, produce a sharp analysis.

            Your analysis must include:
            - SWOT Analysis (Strengths, Weaknesses, Opportunities, Threats)
              Each point should be specific to this company, not generic
            - Three scores out of 10:
                * Market Potential (how big and growing is the opportunity?)
                * Competition Intensity (how crowded and fierce is the market?)
                * Execution Difficulty (how hard is it to build and scale this?)
            - One paragraph verdict: would you recommend pursuing this or not, and why?

            Be honest. Be direct. No sugarcoating.
        """,
        expected_output="""
            A structured analysis with:
            - SWOT table (4 sections, 3-4 bullet points each)
            - Scores section with number and one-line reasoning for each
            - Verdict paragraph (5-7 sentences, direct and specific)
        """,
        agent=analysis_agent,
        context=[research_task],
    )


    report_task = Task(
        description=f"""
            You have received research and analysis about {company_name}.
            Write a final intelligence brief that a busy VC or founder
            can read in under 5 minutes.

            The report must:
            - Open with a one-paragraph executive summary (the most important thing first)
            - Include all key research findings (condensed, not repeated verbatim)
            - Include the full SWOT and scores from the analysis
            - End with a clear final verdict and 2-3 specific things to watch
            - Use markdown formatting (headers, bullet points, bold for key terms)
            - Feel like it was written by a human analyst, not generated by AI
        """,
        expected_output="""
            A complete markdown intelligence brief with these sections:
            # {company_name} — Intelligence Brief
            ## Executive Summary
            ## Company Overview
            ## Market & Competition
            ## SWOT Analysis
            ## Scores
            ## Verdict & Watch Points

            Clean, readable, professional. Under 800 words total.
        """,
        agent=report_agent,
        context=[research_task, analysis_task],
        output_file="outputs/report.md",
    )

    return [research_task, analysis_task, report_task]